name: meals
description: Flutter app that uses Clean Architecture with Bloc and the themealdb.com API.
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.1.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    bloc: ^8.1.2
    equatable: ^2.0.5
    get_it: ^7.6.4
    flutter_bloc: ^8.1.3
    connectivity_plus: ^4.0.2
    dartz: ^0.10.1
    dio: ^5.3.3
    url_launcher: ^6.1.14
    window_manager: ^0.3.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.3
    flutter_launcher_icons: ^0.13.1

flutter:
    uses-material-design: true

flutter_launcher_icons:
    image_path: 'assets/icon/icon.png'
    android: true
    ios: true
    windows:
        generate: true
        icon_size: 48 # min:48, max:256, default: 48
    macos:
        generate: true
# dart pub get
# dart run flutter_launcher_icons
